---
# tasks file for nginx
-name: 'Install nginx with apt'
  become: true
  apt:
    pkg:
    - nginx
    state: latest
    update_cache: true
-name: 'Make sure nginx service is started'
  become: true
  service: 
    name: started

-name: 'Configure Nginx to be a load balancer'
  become: true
  template:
    src: nginx.conf 
    dest: /etc/nginx/nginx.conf
  notify: 'reload nginx'