---
# tasks file for docker
- name: Install Prerequisites
  become: true
  apt: 
    pkg:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg 
      - lsb-release
      - python3
      - python3-pip
    state: latest
    update_cache: true

- name: Get Keys
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|lower }} stable
    state: present

- name: Install Docker packages
  become: true
  apt: 
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker.io
    state: latest
    update_cache: true

- name: Modify users
  become: true
  user:
    name: "{{ item.username }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: Install Ansible Prerequisites
  become: true
  pip: 
    name: docker-py


